FROM nginx:latest

RUN useradd -m -s /bin/bash -u 1000 weather
ARG APP_HOST

# set timezone
RUN cp /etc/localtime /etc/localtime.org && \
    ln -sf  /usr/share/zoneinfo/Asia/Manila /etc/localtime

# nginx.conf
ADD ./infra/web/nginx.conf /etc/nginx/nginx.conf
ADD ./infra/web/vhost.conf /etc/nginx/conf.d/default.conf.template

RUN envsubst '$$APP_HOST' < /etc/nginx/conf.d/default.conf.template > /etc/nginx/conf.d/default.conf

WORKDIR /var/www
